CREATE TABLE CUSTOMER ( 
 CUSTOMERID SMALLINT NOT NULL, 
 "NAME" CHAR(20) 
DEFAULT '[n/a]' NOT NULL, 
 ADRESA CHAR(30)  
DEFAULT '[n/a]');
 
ALTER TABLE CUSTOMER ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY 
(CUSTOMERID); 
 
CREATE TABLE "ORDER" ( 
 ORDERID SMALLINT NOT NULL, 
 DATA DATE DEFAULT 'NOW' NOT NULL, 
 CUSTOMERID SMALLINT NOT NULL, 
 VALOARE DECIMAL(12, 2) DEFAULT 0.0); 
 
 
ALTER TABLE "ORDER" ADD CONSTRAINT PK_ORDER 
PRIMARY KEY (ORDERID); 
 
ALTER TABLE "ORDER" ADD CONSTRAINT FK_ORDER FOREIGN KEY 
 (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID) 
 ON DELETE CASCADE; 
 
CREATE TABLE ORDERDETAILS ( 
 ORDERID SMALLINT NOT NULL, 
 PRODUS CHAR(20)
DEFAULT '[n/a]' NOT NULL, 
 VALOARE DECIMAL(12, 2) DEFAULT 0.0 NOT NULL, 
 SERIAL SMALLINT DEFAULT 0 NOT NULL); 
 
 
ALTER TABLE ORDERDETAILS ADD CONSTRAINT PK_ORDERDETAILS 
 PRIMARY KEY (ORDERID,SERIAL); 
 
ALTER TABLE ORDERDETAILS ADD CONSTRAINT FK_ORDERDETAILS 
 FOREIGN KEY (ORDERID) REFERENCES "ORDER"(ORDERID) 
 ON DELETE CASCADE; 
